// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwY_5EQrVitGO6MhUOt8N-aqlPiRzCKqM',
    appId: '1:768978703800:web:47fe986af1ca164aa5eb4d',
    messagingSenderId: '768978703800',
    projectId: 'qlct-1b2a7',
    authDomain: 'qlct-1b2a7.firebaseapp.com',
    storageBucket: 'qlct-1b2a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC54GkyPTg0MBvRo95YASCZHD7rXzc-VZw',
    appId: '1:768978703800:android:c8d4d657c2a6298ea5eb4d',
    messagingSenderId: '768978703800',
    projectId: 'qlct-1b2a7',
    storageBucket: 'qlct-1b2a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRojdzmyn-bFlaZZaN62e5NKArNsIpJR0',
    appId: '1:768978703800:ios:64864abe7a23cac7a5eb4d',
    messagingSenderId: '768978703800',
    projectId: 'qlct-1b2a7',
    storageBucket: 'qlct-1b2a7.firebasestorage.app',
    iosBundleId: 'com.example.doan',
  );
}
